jobs:
  build:
    working_directory: ~/build
    executor:
      name: node/default
      tag: '10.16'
    steps:
      - checkout
      - run: echo -e "$GPG_KEY" | gpg --import
      - run: gpg --list-secret-keys --keyid-format LONG
      - node/with-cache:
          steps:
            - run: npm install

  publish:
    working_directory: ~/build_and_publish
    executor:
      name: node/default
      tag: '10.16'
    steps:
      - run: echo Publish commerce_sdk to npm
      - checkout
      - add_ssh_keys:
          fingerprints:
            - $GITHUB_HOST_SSH_KEY
      - node/with-cache:
          steps:
            - run: npm install
      - run: echo -e "$GPG_KEY" | gpg --import
      - run: gpg --list-secret-keys --keyid-format LONG
      - run: git config --global user.email "$GITHUB_PUBLISH_EMAIL"
      - run: git config --global user.name "$GITHUB_PUBLISH_USER"
      - run: git config --global user.signingkey $GITHUB_GPG_SIGN_KEY_ID
      - run: git config --global commit.gpgsign true
      - run:
          name: Create npmrc file to authenticate with npm registry.
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npm run publish

workflows:
  version: 2
  build-only:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /^release.*/
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - /^release.*/
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - /^release.*/
      - publish:
          requires:
            - hold
          filters:
            branches:
              only:
                - /^release.*/
orbs:
  node: circleci/node@1.1
version: 2.1

