version: 2.1

parameters:
  publish_npm:
    type: boolean
    default: false

jobs:
  build:
    executor:
      name: node/default
      tag: '10.16'
    steps:
      - checkout
      - run: echo "Kannan test"
      - run: echo inside second job
      - run: echo publish_npm param = << parameters.publish_npm >>
      - run: cat << parameters.file >>
orbs:
  node: circleci/node@1.1
