jobs:
  build:
    working_directory: ~/build
    executor:
      name: node/default
      tag: '10.16'
    steps:
      - checkout
      - run: echo $GITHUB_OAUTH_TOKEN_OWNER , token = $GITHUB_OAUTH_TOKEN, project repo $CIRCLE_PROJECT_REPONAME, branch $CIRCLE_BRANCH, sha1 $CIRCLE_SHA1
      - run: >
          curl 'https://api.github.com/repos/$GITHUB_OAUTH_TOKEN_OWNER/$CIRCLE_PROJECT_REPONAME/pulls' -X POST -H 'Content-Type: application/json' -H 'Authorization: token c4cd9441d4cd982680c21a644fbe9c7269ed22b3' -H 'Accept: application/vnd.github.v3+json' -d '{"title":"Publish from $CIRCLE_BRANCH","body":"Merge publish to master from $CIRCLE_BRANCH with commit sha1 as $CIRCLE_SHA1","head":"$CIRCLE_BRANCH","base":"master"}'
      - run: echo -e "$GPG_KEY" | gpg --import
      - node/with-cache:
          steps:
            - run: npm install

  publish:
    working_directory: ~/build_and_publish
    executor:
      name: node/default
      tag: '10.16'
    steps:
      - run: echo Publish commerce_sdk to npm
      - checkout
      # Add read/write ssh key's finger print in order to push the tags
      - add_ssh_keys:
          fingerprints:
            - "ce:87:9b:64:30:84:54:85:fd:b9:9f:12:8b:11:8d:67"
      - node/with-cache:
          steps:
            - run: npm install
      - run: echo -e "$GPG_KEY" | gpg --import
      - run: gpg --list-secret-keys --keyid-format LONG
      - run: git config --global user.email "$GITHUB_PUBLISH_EMAIL"
      - run: git config --global user.name "$GITHUB_PUBLISH_USER"
      - run: git config --global user.signingkey $GITHUB_GPG_SIGN_KEY_ID
      - run: git config --global commit.gpgsign true
      - run:
          name: Create npmrc file to authenticate with npm registry.
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npm run publish
      - run: >
          curl 'https://api.github.com/repos/$GITHUB_OAUTH_TOKEN_OWNER/$CIRCLE_PROJECT_REPONAME/pulls'
          -X POST
          -H "Content-Type: application/json"
          -H "Authorization: token $GITHUB_OAUTH_TOKEN"
          -H "Accept: application/vnd.github.v3+json"
          -d '{"title":"Publish from $CIRCLE_BRANCH","body":"Merge publish to master from $CIRCLE_BRANCH with commit sha1 as $CIRCLE_SHA1","head":"$CIRCLE_BRANCH","base":"master"}'

workflows:
  version: 2
  build-only:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /^release.*/
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - /^release.*/
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - /^release.*/
      - publish:
          requires:
            - hold
          filters:
            branches:
              only:
                - /^release.*/
orbs:
  node: circleci/node@1.1
version: 2.1

