version: 2.1

parameters:
  publish_npm:
    type: boolean
    default: false

jobs:
  build:
    working_directory: ~/build_and_publish
    executor:
      name: node/default
      tag: '10.16'
    steps:
      - checkout
      - run: echo "Kannan test"
      - run: echo inside second job
      - run: echo publish_npm param = << pipeline.parameters.publish_npm >>
      - persist_to_workspace:
          root: ~/
          paths: .
  publish:
    working_directory: ~/build_and_publish
    executor:
      name: node/default
      tag: '10.16'
    steps:
      - run: echo Publish commerce_sdk to npm
      - when:
          condition: << pipeline.parameters.publish_npm >>
          steps:
            - run: echo inside condition << pipeline.parameters.publish_npm >>
            - attach_workspace:
                at: ~/build_and_publish
            - run: echo Publish commerce_sdk to npm
            - run:
                name: Authenticate with registry
                command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            - run: echo using lerna publish
workflows:
  version: 2
  build-only:
    jobs:
      - build
  build-and-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - publish:
          requires:
            - hold
orbs:
  node: circleci/node@1.1
