version: 2.1

parameters:
  publish_npm:
    type: boolean
    default: false

jobs:
  build:
    working_directory: ~/build_and_publish
    executor:
      name: node/default
      tag: '10.16'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: echo "Kannan test"
      - run: mkdir dist
      - run: touch ./dist/test.log
      - run: echo inside second job
      - run: echo publish_npm param = << pipeline.parameters.publish_npm >>
      - persist_to_workspace:
          root: ~/build_and_publish
          paths: .
  publish:
    working_directory: ~/build_and_publish
    executor:
      name: node/default
      tag: '10.16'
    steps:
      - run: echo Publish commerce_sdk to npm
      - when:
          condition: << pipeline.parameters.publish_npm >>
          steps:
            - run: ls -lart ~/
            - run: ls -lart ~/build_and_publish
            - run: echo inside condition << pipeline.parameters.publish_npm >>
            - attach_workspace:
                at: ~/build_and_publish
            - run:
                name: Authenticate with registry
                command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            - run: echo print npmrc, establish known host for github and Publish commerce_sdk to npm
            - run: cat ~/.npmrc
            - run: npm run publish
workflows:
  version: 2
  build-only:
    unless: << pipeline.parameters.publish_npm >>
    jobs:
      - build
  build-and-deploy:
    when: << pipeline.parameters.publish_npm >>
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - publish:
          requires:
            - hold
orbs:
  node: circleci/node@1.1
