version: 2.1

parameters:
  publish_npm:
    type: boolean
    default: false

jobs:
  build:
    working_directory: ~/build_and_publish
    executor:
      name: node/default
      tag: '10.16'
    steps:
      - add_ssh_keys:
          fingerprints:
            - "78:6d:b4:67:eb:35:d4:a0:63:af:c2:32:f1:94:9a:5f"
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: echo "Kannan test"
      - run: echo inside second job
      - run: echo publish_npm param = << pipeline.parameters.publish_npm >>
      - persist_to_workspace:
          root: ~/build_and_publish
          paths: .
  publish:
    working_directory: ~/build_and_publish
    executor:
      name: node/default
      tag: '10.16'
    steps:
      - run: echo Publish commerce_sdk to npm
      - when:
          condition: << pipeline.parameters.publish_npm >>
          steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                  - "78:6d:b4:67:eb:35:d4:a0:63:af:c2:32:f1:94:9a:5f"
            - run: ls -lart ~/
            - run: mkdir -p ~/.ssh
            - run: ls -lart ~/
            - run:
                command: echo ‘github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==‘ >> ~/.ssh/known_hosts
            - run: cat ~/.ssh/known_hosts

            - run: echo inside condition << pipeline.parameters.publish_npm >>
            - run:
                name: "Configuring git"
                command: |
                  git config --global user.email "kalagarraj@salesforce.com"
                  git config --global user.name "kalagarraj"
            - attach_workspace:
                at: ~/build_and_publish
            - run:
                name: Authenticate with registry
                command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            - run: echo print npmrc, establish known host for github and Publish commerce_sdk to npm
            - run: cat ~/.npmrc
            - run: npm run publish
workflows:
  version: 2
  build-only:
    unless: << pipeline.parameters.publish_npm >>
    jobs:
      - build
  build-and-deploy:
    when: << pipeline.parameters.publish_npm >>
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - publish:
          requires:
            - hold
orbs:
  node: circleci/node@1.1
